"""add tables compilations

Revision ID: 1b3cbd01858e
Revises: b67e25e13609
Create Date: 2023-06-15 17:47:32.853714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3cbd01858e'
down_revision = 'b67e25e13609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compilations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_compilations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compilations'))
    )
    op.create_table('compilations_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_compilation', sa.Integer(), nullable=True),
    sa.Column('id_book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_book'], ['books.id'], name=op.f('fk_compilations_books_id_book_books')),
    sa.ForeignKeyConstraint(['id_compilation'], ['compilations.id'], name=op.f('fk_compilations_books_id_compilation_compilations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compilations_books'))
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_books_cover_id_covers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_books_cover_id_covers'), 'covers', ['cover_id'], ['id'])

    with op.batch_alter_table('genres_books', schema=None) as batch_op:
        batch_op.drop_constraint('fk_genres_books_id_book_books', type_='foreignkey')
        batch_op.drop_constraint('fk_genres_books_id_genre_genres', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_genres_books_id_book_books'), 'books', ['id_book'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_genres_books_id_genre_genres'), 'genres', ['id_genre'], ['id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_book_id_books', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_book_id_books'), 'books', ['book_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_book_id_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_user_id_users', 'users', ['user_id'], ['id'], onupdate='CASCADE')
        batch_op.create_foreign_key('fk_reviews_book_id_books', 'books', ['book_id'], ['id'], onupdate='CASCADE')

    with op.batch_alter_table('genres_books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_genres_books_id_genre_genres'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_genres_books_id_book_books'), type_='foreignkey')
        batch_op.create_foreign_key('fk_genres_books_id_genre_genres', 'genres', ['id_genre'], ['id'], onupdate='CASCADE')
        batch_op.create_foreign_key('fk_genres_books_id_book_books', 'books', ['id_book'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_books_cover_id_covers'), type_='foreignkey')
        batch_op.create_foreign_key('fk_books_cover_id_covers', 'covers', ['cover_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    op.drop_table('compilations_books')
    op.drop_table('compilations')
    # ### end Alembic commands ###
